// Class automatically generated by Dev-C++ New Class wizard

#include "hexagon/Shape.hpp"    // class's header file

namespace hexagon {

// class constructor
Shape::Shape(int type) {
    // insert your code here
}

// class destructor
Shape::~Shape() {
    // insert your code here
}

} // namespace hexagon
