/// Class automatically generated by Dev-C++ New Class wizard

#ifndef SHAPE_H
#define SHAPE_H

namespace hexagon {

/**
 * @class Shape
 * @brief Creates default shapes for the view.
 */
class Shape {
public:
    /// class constructor
    Shape(int type);
    /// class destructor
    ~Shape();
};


} // namespace hexagon

#endif    // SHAPE_H
