// Class automatically generated by Dev-C++ New Class wizard

#ifndef SHAPE_H
#define SHAPE_H

// Creates default shapes for the view.
class Shape
{
	public:
		// class constructor
		Shape(int type);
		// class destructor
		~Shape();
};

#endif // SHAPE_H

