// Class automatically generated by Dev-C++ New Class wizard

#include "Shape.h" // class's header file

// class constructor
Shape::Shape(int type)
{
	// insert your code here
}

// class destructor
Shape::~Shape()
{
	// insert your code here
}

